name: sloth-binder
channels:
  - defaults
  - conda-forge
dependencies:
  - gcc
  - cython
  - qt
  - pyqt=5
  - python=3.6
  - numpy
  - matplotlib
  - scipy
  - pandas
  - jupyter
  - h5py
  - sqlalchemy
  - ipywidgets
  #conda-forge
  - xraylib
  - peakutils
  - lmfit
  - asteval
  - psutil
  - pytest
  - pip:
    - fisx
    - silx
    - pymca
    - fabio
    - hdf5plugin
    - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.1.24-cp36-cp36m-linux_x86_64.whl
